### ISSUE TITLE
Can't invoke scoop after installation

### ISSUE THREAD

**Issue by cap10morgan** [sharpninja/install-scoop-action#1]
When I run this workflow:

```yaml
- name: Install scoop (Windows)
  uses: sharpninja/install-scoop-action@master
- name: Setup Clojure (Windows)
  shell: powershell
  run: |
    scoop bucket add scoop-clojure https://github.com/littleli/scoop-clojure
    scoop install clojure
```

I get this error:

```
scoop : The term 'scoop' is not recognized as the name of a cmdlet, function, script file, or operable program. Check 
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At D:\a\_temp\3e12d7e0-66f5-4c31-80f4-b6350597e05a.ps1:2 char:1
+ scoop bucket add scoop-clojure https://github.com/littleli/scoop-cloj ...
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (scoop:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

Error: Process completed with exit code 1.
```
